js {
  const { buildSelect, loadMeta } = require("../includes/lib");
  const meta = loadMeta("../includes/metadata/lfa1.json");
  const selectList = buildSelect({
    meta,
    sourceAlias: "s",
    surrogateKeyStrategy: dataform.vars().surrogateKeyStrategy
  });
}

config {
  type: "table",
  schema: dataform.vars().targetSchema,
  name: "lfa1",
  tags: ["sap", "lfa1", "target"]
}

select
  {{ selectList }}
from
  ${ref(dataform.vars().stagingSchema, "stg_lfa1")} as s