js {
  const { buildSelect, loadMeta } = require("../includes/lib");
  const meta = loadMeta("../includes/metadata/payr.json");
  const selectList = buildSelect({
    meta,
    sourceAlias: "s",
    surrogateKeyStrategy: dataform.vars().surrogateKeyStrategy
  });
}

config {
  type: "table",
  schema: dataform.vars().targetSchema,
  name: "payr",
  tags: ["sap", "payr", "target"]
}

select
  {{ selectList }}
from
  ${ref(dataform.vars().stagingSchema, "stg_payr")} as s